@startuml
    interface JpaRepository<T,ID> {
      + save(entity: T): T
      + findById(id: ID): Optional<T>
      + findAll(): List<T>
      + deleteById(id: ID): void
      + count(): long
    }

    interface UserRepository<User, Long> {
      + findByUserName(userName: String): Optional<User>
      + findByStaffID(staffID: String): Optional<User>
      + findByAdminID(adminID: String): Optional<User>
    }

    JpaRepository <|-- UserRepository

    UserRepository ..> User : uses

    UserRepository ..> "Optional<User>" : returns

    note right of UserRepository
      User class is found in ./Models.puml
      Additionally UserRepository extends JpaRepository and passes <User, Long>
    end note

@enduml