@startuml
'https://plantuml.com/class-diagram

interface User {
    # username: String
    # password: String
    # dateCreated: Date
    # dateUpdated: Date

    + validatePassword(password: String): boolean
    + fetchInventory(): Inventory
}

class Staff {
    - staffID: String

    + restockIngredient(ingredientID: String, quantity: int): void
    + useRecipe(recipeID: String): Recipe
}

class Admin {
    - adminID: String

    + inviteStaff(email: String): void
    + createIngredient(ingredientID: String): void
    + createRecipe(recipeID: String): void
    + createReport(reportID: String): void

    + fetchIngredient(): Ingredient
    + fetchRecipe(): Recipe
    + fetchReport(): Report
    + fetchStaff(): Staff
}

User <|-- Staff
User <|-- Admin

@enduml